# Generated by Django 3.0.3 on 2020-03-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('accession', models.CharField(db_index=True, max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_from', models.IntegerField()),
                ('pos_to', models.IntegerField()),
                ('sequence', models.TextField()),
                ('sequence_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.Sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('pfam_id', models.CharField(db_index=True, max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sequences', models.ManyToManyField(to='sdb.Sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residues', models.TextField()),
                ('score', models.FloatField()),
                ('family_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.Family')),
            ],
        ),
    ]
