# Generated by Django 3.0.3 on 2020-04-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfam_id', models.CharField(db_index=True, max_length=7)),
                ('score', models.FloatField()),
                ('N', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residues', models.TextField()),
                ('conformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.Conformation')),
            ],
        ),
    ]
