# Generated by Django 3.0.3 on 2020-03-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdb', '0002_community_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('family_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.Family')),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='family_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.Conformation'),
        ),
    ]
