# Generated by Django 3.0.3 on 2020-03-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdb', '0004_auto_20200311_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformation',
            name='network',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
