# Generated by Django 3.0.3 on 2020-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdb', '0005_conformation_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='sequences',
            field=models.ManyToManyField(to='sdb.Offset'),
        ),
    ]
